app/examples/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint

blueprint = Blueprint(
    'example',
    __name__,
    url_prefix='',
    template_folder='../templates',
    static_folder='../static'
)


# Load model here or load model from main app/__init__.py
# poetry add transformers --group dev
from transformers import pipeline

# Load default sentiment analysis from Hugingface Hub
sentiment_pipeline = pipeline("sentiment-analysis") 

# class SentimentAnaliser():
#     def __init__(self):
#         self.sentiment_pipeline = pipeline("sentiment-analysis")
       
#     def analyse(self, text: str):
#         return self.sentiment_pipeline(text)

app/examples/controllers.py
# -*- coding: utf-8 -*-
from os import path
import logging
logger = logging.Logger(__name__)

from flask import render_template, session, g, send_from_directory, request
from app import app
from flask_login import login_required, current_user

from app.examples import blueprint, sentiment_pipeline

@blueprint.route('/example/sentiment-analysis', methods=['GET', 'POST'])
#@login_required
def sentiment_analysis():


    if request.method == 'GET':
        return render_template('examples/sentiment-analysis.html', config=app.config, text_value='', sentiment_result='')
    
    # if request.method == 'POST'
    text_value = request.form.get('text_area')

    print(text_value)
    sentiment_predict = sentiment_pipeline([text_value])
    score = sentiment_predict[0]['score']
    if sentiment_predict[0]['label']=='POSITIVE':
        result = f'<i class="fa-solid fa-face-smile" style="color:orange; font-size: 50px;"></i> Positive: {round(score, 3)*100}%'
    elif sentiment_predict[0]['label']=='NEGATIVE':
        result = f'<i class="fa-solid fa-face-sad-tear" style="color:orange; font-size: 50px;"></i> Negative: {round(score, 3)*100}%'
    else:
        result = f'<i class="fa-solid fa-face-meh" style="color:orange; font-size: 50px;"></i> Neutral: {round(score, 3)*100}%'

    return render_template('examples/sentiment-analysis.html', 
            config=app.config, 
            text_value=text_value, 
            sentiment_result=result)

app/templates/examples/sentiment-analysis.html
{% extends "layouts/base.html" %}

{% macro sentence_case(text) %}
    {{ text[0]|upper}}{{text[1:] }}
{% endmacro %}

{% block headscripts %}

{% endblock headscripts %}

<!-- Element injected in the BODY element layout-top-nav -->
{% block body_class %} sidebar-mini sidebar-collapse {% endblock body_class %}

<!-- CSS goes HERE  -->
{% block stylesheets %}

<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<script src="https://kit.fontawesome.com/0b0bc30e16.js" crossorigin="anonymous"></script>

<!-- style -->
<link rel="stylesheet" href="/static/css/adminlte.min.css?v=3.2.0">
<link rel="stylesheet" href="/static/css/style.css?v=20">
{% endblock stylesheets %}

{% block content %}
<div class="content-wrapper">

    <!-- Main content -->
    <section class="content">

        <div class="container-fluid">
            <div class="page-header">
              <label>
                  Sentiment analysis demo
              </label>
            </div>
            <div class="row">
              <div class="col-8">
                <!-- Text area -->
                <form action="{{ url_for('example.sentiment_analysis') }}" method="post" id="myform">
                    <label for="text_area">Enter a document content</label>
                    <textarea name="text_area" id="text_area" form="myform" style="width:100%;"
                      placeholder="Enter your content here for Sentiment Analysis" rows="14">{{ text_value }}</textarea>
                    
                    <input type="submit" value="Submit" class="bg-primary">
                </form>
              </div>

              <div class="col-4">
                <label>Results: </label> <br>
                {{sentiment_result|safe}}
              </div>
              
            </div>
            
        </div>
    </section>
</div>
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<!-- jQuery -->
<script
  src="https://code.jquery.com/jquery-3.6.3.min.js"
  integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
  crossorigin="anonymous"></script>

<!-- Bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

<!-- AdminLTE -->
<script src="/static/js/adminlte.js"></script>

{% endblock javascripts %}